FROM wangjianshou/alpine:3.8
RUN apk update --no-cache && \
    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk && \
    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-bin-2.28-r0.apk && \
    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-dev-2.28-r0.apk && \
    wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-i18n-2.28-r0.apk && \
    apk add --allow-untrusted glibc-2.28-r0.apk glibc-bin-2.28-r0.apk glibc-dev-2.28-r0.apk glibc-i18n-2.28-r0.apk && \
    /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 C.UTF-8 && \
    rm glibc-2.28-r0.apk && rm glibc-bin-2.28-r0.apk && rm  glibc-dev-2.28-r0.apk && rm glibc-i18n-2.28-r0.apk && \
    rm -rf /var/cache/apk/*
# /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
# /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 C.UTF-8 //for shogun
