FROM wangjianshou/alpine3.8-glibc:glibc_2.28
RUN apk update -q --no-cache && \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    mkdir -p /opt/miniconda && \
    sh miniconda.sh -bfp /opt/miniconda && \
    ln -s /opt/miniconda/etc/profile.d/conda.sh /etc/profile.d/ && \
    echo ". /opt/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    rm miniconda.sh && \
    rm -r /opt/miniconda/pkgs
